/**
 * Regenerate `COMPATIBILITY.md` from the current package metadata.
 *
 * The matrix lists each package's latest version alongside the spec version
 * range it claims to implement (read from manifest metadata).
 */

import { writeFile } from 'node:fs/promises';

import type { ReleaseConfig } from './config.js';

const HEADER = `<!--
  This file is generated by \`pnpm release version\` (and re-generated on every
  release). Edit the metadata in each package's manifest, not this file.
-->

# Compatibility matrix

`;

const FOOTER = `
Each implementation declares its supported spec range via manifest metadata
(\`codama.spec\` in \`package.json\`, \`package.metadata.codama.spec\` in \`Cargo.toml\`).
`;

export async function regenerateCompatibility(config: ReleaseConfig): Promise<void> {
    const rows: string[] = [];
    rows.push('| Package | Latest version | Implements spec |');
    rows.push('| --- | --- | --- |');

    const ordered = [...config.packages.values()]
        .filter(p => !p.private)
        .sort((a, b) => {
            if (a.ecosystem !== b.ecosystem) return a.ecosystem === 'js' ? -1 : 1;
            return a.name.localeCompare(b.name);
        });

    for (const pkg of ordered) {
        const spec = pkg.specRange ?? '—';
        rows.push(`| \`${pkg.name}\` | \`${pkg.version}\` | \`${spec}\` |`);
    }

    const body = `${HEADER}${rows.join('\n')}\n${FOOTER}`;
    await writeFile(config.compatibilityPath, body, 'utf8');
}
